### ISSUE TITLE
Secure mode hazard

### ISSUE THREAD

**Issue by WebReflection** [syg/proposal-symbol-proto#3]
> Enable secure mode when Symbol.proto/constructor is used at least once.

This breaks every bundled asset in the wild as soon as any relevant to irrelevant library uses `Symbol.proto` that, once bundled together with any other code that can't prevent that, or be aware of.

This is not an option at all if we consider the current state of the Web and its deployment.

> Introduce a use secure-mode directive or an Object.enableSecureMode() API

AFAIK / IIRC directives are not an option anymore (for better or worse results) but directives can be easily scoped and are static, while `Object.enableSecureMode()` could be invoked by accident via `Object[shenanigan]()`.

It was a bit awkward to find `use "secure-mode"` as option, but definitively it's not clear why or how `Object.enableSecureMode()` should work and where that mode is secured (in scope? globally? in latter case, see previous point).

> Introduce an out-of-band mechanism to enable secure mode

This seems to be the only non-breaking option and it gives all the footguns to the site/application owner so I suggest going forward with this idea (if others are the only alternatives).

Ideally, this should / could be a CSP policy so that it can incrementally be added but that won't work on NodeJS or non HTTP based projects and I am afraid `.sjs` is already taken as extension so that the `use "secure-mode"` looks like the best option yet it would be a step backward into the language (imho the best solution to these exact problems though).

**Comment by salcho** [comment]
Hey Andrea, full agreement! I've pushed an updated version of this proposal that emphasises the out-of-band mechanism and simply mentions alternatives considered. Also, thanks for the added context on directives not being an option anymore. Please take a look at the updated content!
